# pandas

### Partie 1

Installer et importer pandas et numpy et afficher leur versions

In [1]:
import pandas as pd
print(pd.__version__)

1.1.4

In [2]:
import numpy as np
print(np.__version__)

1.19.4

Transformer ces variables en Pandas Series

In [3]:
liste = list(range(0, 17))
dictionary = {"A":  0, "B":1, "C":2, "D":3, "E":5}

In [4]:
pd.Series(liste)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
dtype: int64

In [5]:
pd.Series(dictionary)

A    0
B    1
C    2
D    3
E    5
dtype: int64

 - Afficher la variable dictionnaire
 - Transformer le dictionnaire en dataframe

In [6]:
dictionaire = {x:np.random.randint(0,100,50) for x in "ABCDE"}
pd.Series(dictionaire)

A    [24, 69, 59, 23, 7, 68, 15, 21, 47, 57, 29, 35...
B    [51, 15, 31, 60, 70, 22, 16, 26, 43, 38, 42, 8...
C    [99, 45, 95, 83, 12, 80, 78, 66, 20, 5, 16, 48...
D    [99, 47, 54, 51, 75, 35, 65, 16, 1, 95, 47, 56...
E    [39, 93, 74, 65, 3, 72, 70, 27, 21, 61, 52, 26...
dtype: object

In [34]:
df = pd.DataFrame(dictionaire)
print(df)

     A   B   C   D   E
0   24  51  99  99  39
1   69  15  45  47  93
2   59  31  95  54  74
3   23  60  83  51  65
4    7  70  12  75   3
5   68  22  80  35  72
6   15  16  78  65  70
7   21  26  66  16  27
8   47  43  20   1  21
9   57  38   5  95  61
10  29  42  16  47  52
11  35  89  48  56  26
12  72  41  46  30  10
13  11  51  51  47  23
14  53   3  61  97  84
15  53  69  53  61   3
16  18  27  80  71   8
17  18  45  26  81  56
18   3  64  49  95  43
19   5  65  50  82  15
20  36  65  86  23  80
21   1  54  54  11  85
22   3  62  24   7  36
23  81  48  68  14  17
24  51  30  44  73  20
25  66  68  19  86  87
26  84   4  92  69  35
27  80   5  33  44  89
28  11  45  40   8  14
29  11  72  63  73  80
30  65  86  62  12  75
31  68   5   5  82  22
32  35  90  80  78   5
33  81  59  79  44   1
34  80  33  79  71  45
35   0  42  36  23  91
36  34  26  60  26  92
37  15  22  41  40  57
38  77  58  32  75  64
39  32   7  69  74  69
40  57  77  14  95  50
41  22  19  68  84  44
42  89  63  22  60  28
43  95  34  84  36  29
44   4  76  48   7   5
45  95   2  39  80  54
46  14  59  52  39  80
47   6  46  96  44  99
48  97   1  95  14  13
49  52  87  68  38   3

Trouver comment  afficher un descriptif de ce dataframe

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       50 non-null     int64
 1   B       50 non-null     int64
 2   C       50 non-null     int64
 3   D       50 non-null     int64
 4   E       50 non-null     int64
dtypes: int64(5)
memory usage: 2.1 KB

In [9]:
df.describe()

               A          B          C          D          E
count  50.000000  50.000000  50.000000  50.000000  50.000000
mean   42.580000  44.260000  54.300000  52.700000  46.280000
std    30.344344  25.440455  26.071526  28.579463  30.447037
min     0.000000   1.000000   5.000000   1.000000   1.000000
25%    15.000000  26.000000  36.750000  31.250000  20.250000
50%    35.500000  45.000000  52.500000  52.500000  44.500000
75%    68.000000  63.750000  78.750000  75.000000  73.500000
max    97.000000  90.000000  99.000000  99.000000  99.000000

Afficher le nombre de fois que chacune des valeurs apparait dans chaque colonne

In [10]:
df.A.value_counts()

11    3
35    2
57    2
81    2
80    2
15    2
95    2
18    2
68    2
3     2
53    2
65    1
7     1
84    1
72    1
69    1
77    1
14    1
66    1
1     1
59    1
22    1
21    1
23    1
24    1
89    1
29    1
32    1
97    1
34    1
36    1
4     1
5     1
47    1
51    1
52    1
6     1
0     1
Name: A, dtype: int64

In [11]:
df.B.value_counts()

42    2
51    2
26    2
45    2
5     2
22    2
65    2
59    2
68    1
76    1
19    1
86    1
16    1
15    1
77    1
1     1
3     1
72    1
7     1
87    1
70    1
2     1
69    1
63    1
27    1
89    1
41    1
60    1
58    1
54    1
90    1
48    1
43    1
38    1
62    1
4     1
46    1
34    1
33    1
31    1
30    1
64    1
Name: B, dtype: int64

In [12]:
df.C.value_counts()

68    3
80    3
5     2
95    2
79    2
48    2
63    1
20    1
32    1
92    1
26    1
24    1
16    1
14    1
83    1
99    1
86    1
78    1
12    1
19    1
33    1
36    1
62    1
69    1
61    1
60    1
96    1
54    1
53    1
52    1
51    1
50    1
49    1
22    1
46    1
45    1
44    1
84    1
41    1
40    1
39    1
66    1
Name: C, dtype: int64

In [13]:
df.D.value_counts()

44    3
95    3
47    3
14    2
7     2
71    2
82    2
73    2
23    2
75    2
84    1
81    1
16    1
61    1
12    1
1     1
8     1
69    1
65    1
86    1
30    1
26    1
80    1
74    1
97    1
99    1
11    1
38    1
39    1
40    1
36    1
60    1
78    1
51    1
54    1
56    1
35    1
Name: D, dtype: int64

In [14]:
df.E.value_counts()

3     3
80    3
5     2
28    1
15    1
23    1
22    1
21    1
84    1
1     1
54    1
17    1
14    1
26    1
99    1
75    1
74    1
8     1
72    1
70    1
65    1
89    1
27    1
85    1
92    1
61    1
57    1
56    1
20    1
44    1
52    1
29    1
50    1
87    1
91    1
45    1
10    1
43    1
39    1
69    1
36    1
35    1
13    1
93    1
64    1
Name: E, dtype: int64

Afficher uniquement les valeurs surperieures à 30 de la colonne b

In [15]:
df.B.values[df.B > 30]

array([51, 31, 60, 70, 43, 38, 42, 89, 41, 51, 69, 45, 64, 65, 65, 54, 62,
       48, 68, 45, 72, 86, 90, 59, 33, 42, 58, 77, 63, 34, 76, 59, 46, 87])

Tranformer ces deux listes en series et nommez-les series1 et series2 :
 - Multipliez-les entre elle pour faire une troisième series
 - Combinez-les pour en faire un dataframe

In [37]:
liste1 = list(range(0, 14))
liste2 = list(range(10, 24))

In [42]:
series1 = pd.Series(liste1, name="s1")
series2 = pd.Series(liste2, name="s2")
series3 = series1 * series2
series3.name = "s3"
pd.concat([series1, series2, series3], axis=1)
#print(series1)

    s1  s2   s3
0    0  10    0
1    1  11   11
2    2  12   24
3    3  13   39
4    4  14   56
5    5  15   75
6    6  16   96
7    7  17  119
8    8  18  144
9    9  19  171
10  10  20  200
11  11  21  231
12  12  22  264
13  13  23  299

En partant des series1 et series2, faites 2 series qui comportent uniquement les valeurs:
   - presentes dans la series1 et non dans la series2
   - presentes dans la series2 et non dans la series1

In [18]:
series1[~series1.isin(series2)]

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [19]:
series2[~series2.isin(series1)]

4     14
5     15
6     16
7     17
8     18
9     19
10    20
11    21
12    22
13    23
dtype: int64

Faites de même avec la liste3 et la liste4

In [20]:
liste3 = ["de","bd","ng","us","fr","it"]
liste4 = ["fr","cv","ng","us","bs","it"]

In [21]:
series3 = pd.Series(liste3)
series4 = pd.Series(liste4)
print(series3)

0    de
1    bd
2    ng
3    us
4    fr
5    it
dtype: object

In [22]:
series3[~series3.isin(series4)]

0    de
1    bd
dtype: object

In [23]:
series4[~series4.isin(series3)]

1    cv
4    bs
dtype: object

### Partie 2

Importer la librairie os et creer une fonction avec en argument le path qui teste si le path existe

In [24]:
path = "./databases/database.csv"

In [25]:
import os
def check_path(path: str):
    return os.path.exists(path)

A l'aide des methodes propres à pandas faire un dataframe du csv contenu dans le path

In [44]:
print(check_path(path))
if check_path(path):
    df = pd.read_csv(path)
df

True

/Users/nolwenn/Documents/IPSSI/Python/workbooks/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (16) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
1,2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
2,3,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,0,FBI
3,4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
4,5,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,1,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638449,638450,WY01500,Park County,Sheriff,Park,Wyoming,2014,January,1,Murder or Manslaughter,...,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Handgun,0,0,FBI
638450,638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014,June,1,Murder or Manslaughter,...,Unknown,Male,57,White,Unknown,Acquaintance,Handgun,0,0,FBI
638451,638452,WY01701,Sheridan,Municipal Police,Sheridan,Wyoming,2014,September,1,Murder or Manslaughter,...,Unknown,Female,22,Asian/Pacific Islander,Unknown,Daughter,Suffocation,0,0,FBI
638452,638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014,December,1,Murder or Manslaughter,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0,1,FBI
638453,638454,WY01902,Rock Springs,Municipal Police,Sweetwater,Wyoming,2014,September,1,Murder or Manslaughter,...,Not Hispanic,Female,24,White,Not Hispanic,Daughter,Blunt Object,0,1,FBI

In [27]:
df = pd.read_csv(path)
df

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
1,2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
2,3,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,0,FBI
3,4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
4,5,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,2,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,1,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638449,638450,WY01500,Park County,Sheriff,Park,Wyoming,2014,January,1,Murder or Manslaughter,...,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Handgun,0,0,FBI
638450,638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014,June,1,Murder or Manslaughter,...,Unknown,Male,57,White,Unknown,Acquaintance,Handgun,0,0,FBI
638451,638452,WY01701,Sheridan,Municipal Police,Sheridan,Wyoming,2014,September,1,Murder or Manslaughter,...,Unknown,Female,22,Asian/Pacific Islander,Unknown,Daughter,Suffocation,0,0,FBI
638452,638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014,December,1,Murder or Manslaughter,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0,1,FBI
638453,638454,WY01902,Rock Springs,Municipal Police,Sweetwater,Wyoming,2014,September,1,Murder or Manslaughter,...,Not Hispanic,Female,24,White,Not Hispanic,Daughter,Blunt Object,0,1,FBI

Afficher toutes les colones du dataframe

In [28]:
df.columns

Index(['Record ID', 'Agency Code', 'Agency Name', 'Agency Type', 'City',
       'State', 'Year', 'Month', 'Incident', 'Crime Type', 'Crime Solved',
       'Victim Sex', 'Victim Age', 'Victim Race', 'Victim Ethnicity',
       'Perpetrator Sex', 'Perpetrator Age', 'Perpetrator Race',
       'Perpetrator Ethnicity', 'Relationship', 'Weapon', 'Victim Count',
       'Perpetrator Count', 'Record Source'],
      dtype='object')

afficher le nombre de lignes du dataframe

In [29]:
df.shape[0]

638454

- A l'aide des mask pandas filtrer le dataframe pour afficher voir:  
   - toutes les lignes avec plus d'une victime
   - toutes les lignes avec Perpetrator Sex egale a male
   - le nombre de crime apres les années 2000
   - tout les crime avec plus de 4 victimes commis au mois aout

In [30]:
df[df['Victim Count'] > 1]

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
20,21,AK00118,North Slope Borough,County Police,North Slope,Alaska,1980,August,1,Murder or Manslaughter,...,Unknown,Male,29,Unknown,Unknown,Stepdaughter,Rifle,2,0,FBI
21,22,AK00118,North Slope Borough,County Police,North Slope,Alaska,1980,August,1,Murder or Manslaughter,...,Unknown,Male,29,Unknown,Unknown,Stepdaughter,Rifle,2,0,FBI
24,25,AK00118,North Slope Borough,County Police,North Slope,Alaska,1980,August,1,Murder or Manslaughter,...,Unknown,Male,29,Unknown,Unknown,Stepdaughter,Rifle,2,0,FBI
314,315,AL00800,Blount,Sheriff,Blount,Alabama,1980,April,1,Murder or Manslaughter,...,Not Hispanic,Male,41,White,Not Hispanic,Stranger,Handgun,2,0,FBI
315,316,AL00800,Blount,Sheriff,Blount,Alabama,1980,April,1,Murder or Manslaughter,...,Not Hispanic,Male,41,White,Not Hispanic,Stranger,Handgun,2,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638092,638093,WA02703,Tacoma,Municipal Police,Pierce,Washington,2014,May,1,Murder or Manslaughter,...,Unknown,Male,38,White,Unknown,Friend,Unknown,2,1,FBI
638095,638096,WA02703,Tacoma,Municipal Police,Pierce,Washington,2014,May,1,Murder or Manslaughter,...,Unknown,Male,38,White,Unknown,Friend,Unknown,2,1,FBI
638120,638121,WA03105,Marysville,Municipal Police,Snohomish,Washington,2014,October,1,Murder or Manslaughter,...,Not Hispanic,Male,15,Native American/Alaska Native,Not Hispanic,Friend,Handgun,2,0,FBI
638121,638122,WA03105,Marysville,Municipal Police,Snohomish,Washington,2014,October,1,Murder or Manslaughter,...,Not Hispanic,Male,15,Native American/Alaska Native,Not Hispanic,Friend,Handgun,2,0,FBI
638122,638123,WA03105,Marysville,Municipal Police,Snohomish,Washington,2014,October,1,Murder or Manslaughter,...,Not Hispanic,Male,15,Native American/Alaska Native,Not Hispanic,Friend,Handgun,2,0,FBI

In [31]:
df[df['Perpetrator Sex'] == 'Male']

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
1,2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
3,4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
5,6,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,May,1,Murder or Manslaughter,...,Unknown,Male,36,White,Unknown,Acquaintance,Rifle,0,0,FBI
6,7,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,May,2,Murder or Manslaughter,...,Unknown,Male,27,Black,Unknown,Wife,Knife,0,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638446,638447,WY01300,Natrona County,Sheriff,Natrona,Wyoming,2014,September,1,Murder or Manslaughter,...,Not Hispanic,Male,48,White,Not Hispanic,Mother,Handgun,0,0,FBI
638447,638448,WY01301,Casper,Municipal Police,Natrona,Wyoming,2014,June,1,Murder or Manslaughter,...,Not Hispanic,Male,22,White,Unknown,Girlfriend,Handgun,0,0,FBI
638448,638449,WY01301,Casper,Municipal Police,Natrona,Wyoming,2014,August,1,Murder or Manslaughter,...,Unknown,Male,67,Black,Unknown,Friend,Firearm,0,0,FBI
638450,638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014,June,1,Murder or Manslaughter,...,Unknown,Male,57,White,Unknown,Acquaintance,Handgun,0,0,FBI
638452,638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014,December,1,Murder or Manslaughter,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0,1,FBI

In [32]:
len(df[df['Year'] > 2000])

221351

In [49]:
df[(df['Victim Count'] > 4) & (df['Month'] == 'August') ]

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
49046,49047,FL01300,Miami-Dade,County Police,Dade,Florida,1982,August,13,Murder or Manslaughter,...,Not Hispanic,Male,51,White,Not Hispanic,Unknown,Shotgun,7,0,FBI
49047,49048,FL01300,Miami-Dade,County Police,Dade,Florida,1982,August,13,Murder or Manslaughter,...,Not Hispanic,Male,51,White,Not Hispanic,Unknown,Shotgun,7,0,FBI
49048,49049,FL01300,Miami-Dade,County Police,Dade,Florida,1982,August,13,Murder or Manslaughter,...,Not Hispanic,Male,51,White,Not Hispanic,Unknown,Shotgun,7,0,FBI
49049,49050,FL01300,Miami-Dade,County Police,Dade,Florida,1982,August,13,Murder or Manslaughter,...,Not Hispanic,Male,51,White,Not Hispanic,Unknown,Shotgun,7,0,FBI
49051,49052,FL01300,Miami-Dade,County Police,Dade,Florida,1982,August,13,Murder or Manslaughter,...,Hispanic,Male,51,White,Not Hispanic,Unknown,Shotgun,7,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623893,623894,WI04110,Oak Creek,Municipal Police,Milwaukee,Wisconsin,2012,August,1,Murder or Manslaughter,...,Unknown,Male,40,White,Unknown,Stranger,Handgun,5,0,FBI
623894,623895,WI04110,Oak Creek,Municipal Police,Milwaukee,Wisconsin,2012,August,1,Murder or Manslaughter,...,Unknown,Male,40,White,Unknown,Stranger,Handgun,5,0,FBI
623895,623896,WI04110,Oak Creek,Municipal Police,Milwaukee,Wisconsin,2012,August,1,Murder or Manslaughter,...,Unknown,Male,40,White,Unknown,Stranger,Handgun,5,0,FBI
623896,623897,WI04110,Oak Creek,Municipal Police,Milwaukee,Wisconsin,2012,August,1,Murder or Manslaughter,...,Unknown,Male,40,White,Unknown,Stranger,Handgun,5,0,FBI
623897,623898,WI04110,Oak Creek,Municipal Police,Milwaukee,Wisconsin,2012,August,1,Murder or Manslaughter,...,Unknown,Male,40,White,Unknown,Stranger,Handgun,5,0,FBI

In [50]:
df[(df['Victim Count'] > 4) & (df['Month'] == 'August') ].groupby('State')['Record ID'].count()

State
Connecticut      8
Florida         14
Georgia          8
Illinois         6
Iowa             6
Ohio             6
Oklahoma        10
Pennsylvania    16
Texas           12
Wisconsin        6
Name: Record ID, dtype: int64